apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtls-server-deployment
  namespace: mtls-example
  labels:
    app: mtls-server-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mtls-server
  template:
    metadata:
      labels:
        app: mtls-server
    spec:
      containers:
      - name: mtls-server
        image: englaender/mtls-server-spring
        ports:
          - name: server-service 
            containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: mtls-server-service
  namespace: mtls-example
spec:
  clusterIP: 10.103.92.60
  type: NodePort
  selector:
    app: mtls-server
  ports:
  - port: 8000
    targetPort: server-service
